# Generated by Django 5.1 on 2024-08-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="retried_quiz",
            field=models.BooleanField(default=False),
        ),
    ]
