# Generated by Django 5.1 on 2024-08-22 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_question_retried_quiz"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="retried_quiz",
        ),
    ]
